-- =====================================================
-- NEW TABLES (Fully aligned with existing schema style)
-- =====================================================

-- 1. COURSERATING
CREATE TABLE IF NOT EXISTS COURSERATING (
    "RatingID" SERIAL PRIMARY KEY,
    "CourseID" INT NOT NULL REFERENCES COURSE("CourseID") ON DELETE CASCADE,
    "UserID" INT NOT NULL REFERENCES "USER"("UserID") ON DELETE CASCADE,
    "RatingScore" INT CHECK ("RatingScore" >= 1 AND "RatingScore" <= 5),
    "Comment" TEXT,
    "ReviewedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. SKILLTREE
CREATE TABLE IF NOT EXISTS SKILLTREE (
    "TreeID" SERIAL PRIMARY KEY,
    "CourseID" INT NOT NULL REFERENCES COURSE("CourseID") ON DELETE CASCADE,
    "TreeName" VARCHAR(200) NOT NULL,
    "Status" VARCHAR(20) DEFAULT 'active'
);

-- 3. NODEPREREQUISITES
CREATE TABLE IF NOT EXISTS NODEPREREQUISITES (
    "NodeID" INT NOT NULL REFERENCES NODE("NodeID") ON DELETE CASCADE,
    "PrerequisiteNodeID" INT NOT NULL REFERENCES NODE("NodeID") ON DELETE CASCADE,
    PRIMARY KEY ("NodeID", "PrerequisiteNodeID")
);

-- 4. TASKTYPE
CREATE TABLE IF NOT EXISTS TASKTYPE (
    "TypeID" SERIAL PRIMARY KEY,
    "TypeName" VARCHAR(100) NOT NULL
);

-- 5. TASK
CREATE TABLE IF NOT EXISTS TASK (
    "TaskID" SERIAL PRIMARY KEY,
    "NodeID" INT NOT NULL REFERENCES NODE("NodeID") ON DELETE CASCADE,
    "TypeID" INT NOT NULL REFERENCES TASKTYPE("TypeID") ON DELETE CASCADE,
    "Instruction" TEXT NOT NULL
);

-- 6. ACHIEVEMENT
CREATE TABLE IF NOT EXISTS ACHIEVEMENT (
    "AchievementID" SERIAL PRIMARY KEY,
    "Name" VARCHAR(200) NOT NULL,
    "Description" TEXT,
    "CriteriaType" VARCHAR(100)
);

-- 7. USERACHIEVEMENT
CREATE TABLE IF NOT EXISTS USERACHIEVEMENT (
    "AchievementID" INT NOT NULL REFERENCES ACHIEVEMENT("AchievementID") ON DELETE CASCADE,
    "UserID" INT NOT NULL REFERENCES "USER"("UserID") ON DELETE CASCADE,
    "Date" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("AchievementID", "UserID")
);
